export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const FORMULARIO_INTEGRANTE = 'FORMULARIO_INTEGRANTE';
export const OCULTAR_FORMULARIO = 'OCULTAR_FORMULARIO';
export const OBTENER_INTEGRANTES = 'OBTENER_INTEGRANTES';
export const AGREGAR_INTEGRANTE = 'AGREGAR_INTEGRANTE';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const INTEGRANTE_ACTUAL = 'INTEGRANTE_ACTUAL';
export const ERROR_INTEGRANTE = 'ERROR_INTEGRANTE';

export const FORMULARIO_DEVOCIONAL = 'FORMULARIO_DEVOCIONAL';
export const OCULTAR_FORMULARIO_DEVOCIONAL = 'OCULTAR_FORMULARIO_DEVOCIONAL';
export const OBTENER_DEVOCIONALES = 'OBTENER_DEVOCIONALES';
export const AGREGAR_DEVOCIONAL = 'AGREGAR_DEVOCIONAL';
export const VALIDAR_FORMULARIO_DEVOCIONAL = 'VALIDAR_FORMULARIO_DEVOCIONAL';
export const DEVOCIONAL_ACTUAL = 'DEVOCIONAL_ACTUAL';
export const ERROR_DEVOCIONAL = 'ERROR_DEVOCIONAL';


export const AGREGAR_NUEVO = 'AGREGAR_NUEVO';
