export const homeObjeOne = {
  id: "nosotros",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Haz parte",
  headline: "Conoce más de nosotros",
  description:
    "Queremos conocerte y compartir contigo el maravilloso amor de Dios. El nos ha dado vida nueva en su Hijo Jesucristo.Te invitamos a que conozcas más de de nuestra visión, misión y de nuestra declaración de fé.",
  buttonLabel: "Ver más",
  direction:"/nosotros",
  imgStart: false,
  img: require("../../images/logoinfoicc.svg"),
  alt: "iglesia cruzada cristiana itagÜí",
  dark: false,
  primary: true,
  darkText: true,
};
export const homeObjeTwo = {
  id: "actividades",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Bienvenido",
  headline: "Nuestras Actividades",
  description:
    "Queremos conocerte y compartir contigo el maravilloso amor de Dios. El nos ha dado su perdón y vida nueva en su Hijo Jesucristo. El tiene un gran plan para tu vida ven y conócelo.",
  buttonLabel: "Ver más",
  direction:"/actividades",
  imgStart: true,
  img: require("../../images/activities.svg"),
  alt: "actividades itagüí",
  dark: true,
  primary: false,
  darkText: false,
};
export const homeObjeThree = {
  id: "palabra",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Devocional",
  headline: "Meditemos en la Palabra de Dios",
  description:
    "Te invitamos a que tengas  un tiempo de quietud y recibas una palabra que reconfortará tu corazón. La Palabra de Dios tiene el poder para guiarte, levantarte y sanarte. Haz click aquí abajo. ",
  buttonLabel: "Ver más",
  direction:"/devocionales",
  imgStart: false,
  img: require("../../images/read.svg"),
  alt: "ICC Itagui",
  dark: false,
  primary: true,
  darkText: true,
};
